### PR TITLE
Separate self provisioned and existing cluster docs for Elasticsearch…

### PR DESCRIPTION
**Pull request by objectiser**
… Storage in operator

Signed-off-by: Gary Brown <gary@brownuk.com>

## Which problem is this PR solving?
Current Elasticsearch Storage section of jaeger operator docs focuses on the self provisioned approach.

## Short description of the changes
Separated self provisioned from existing ES cluster support - and included links to cli docs.

### CODE REVIEW

**Comment by yurishkuro** [comment]
@objectiser @jpkrohling what is the status of this PR?

**Comment by jpkrohling** [comment]
I missed this PR. I just reviewed and it looks good. @objectiser, you can merge it after copying that to 1.14/next-release, if you think it's still relevant.

**Comment by yurishkuro** [comment]
@objectiser @jpkrohling do you want to finish this PR?

**Comment by objectiser** [comment]
Will close, as superceded by #324

**Pull request closed without merging**
