### PR TITLE
[WIP]: Fix for RSS feed is crashing the build

### PR DESCRIPTION
**Pull request by chamodshehanka**
## Which problem is this PR solving?
- Closes: https://github.com/jaegertracing/documentation/issues/710

## Description of the changes
- TBD

## How was this change tested?
- TBD

## Checklist
- [ ] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [ ] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [ ] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by yurishkuro** [comment]
You can test changes locally with `make develop`.

To make the testing cycles faster I found it useful to delete most of content/docs/1.xx directories, e.g. leave only 1.58 (but obviously don't commit this way), so that hugo has much fewer pages to process.

**Comment by yurishkuro** [comment]
And please make sure all commits are signed.

**Comment by chamodshehanka** [comment]
> You can test changes locally with `make develop`.
> 
> To make the testing cycles faster I found it useful to delete most of content/docs/1.xx directories, e.g. leave only 1.58 (but obviously don't commit this way), so that hugo has much fewer pages to process.

sure! I'll

**Comment by yurishkuro** [comment]
@chamodshehanka I couldn't push a fix to this PR because you did it from the main branch of your fork - I strongly advise against doing that in the future, always use dedicated branch.

The fix is in https://github.com/jaegertracing/documentation/pull/713

**Comment by chamodshehanka** [comment]
> @chamodshehanka I couldn't push a fix to this PR because you did it from the main branch of your fork - I strongly advise against doing that in the future, always use dedicated branch.
> 
> The fix is in #713

my apologize for that. I won't do that in the future. 
Thanks

**Pull request closed without merging**
