### PR TITLE
Provide hierarchical docs menu

### LINKED ISSUE #45: Make main menu hierarchical
For example, Client Features should really be just a sub-menu under Client Libraries, not the top-level entry.

### PR DESCRIPTION
**Pull request by lucperkins**
Fixes #45.

@yurishkuro This is an initial implementation (just the static site generator scaffolding) but it's ready for review. We can easily change the aesthetic now or later on.

### CODE REVIEW

**Comment by yurishkuro** [comment]
Could the top-level item be a page rather than just a label? 

i.e. instead of
```
Clients
  +--- Libraries
  +--- Features
```

have this:
```
Client libraries
  +--- Features
```

NB: the Docs menu in the top bar doesn't respect the hierarchy, it lists all pages at the end

**Comment by lucperkins** [comment]
@yurishkuro Okay, I've ironed that out in the sidebar. Should have a fix for the top dropdown soon.

**Comment by yurishkuro** [comment]
@lucperkins any last touches for this?

**Comment by lucperkins** [comment]
@yurishkuro Ah, sorry, this fell off the radar for me. Just need to fix the navbar dropdown.

**Comment by yurishkuro** [comment]
probably the footer on the home page too (don't show 2nd level items)

thanks!

**Pull request merged**
