### PR TITLE
Fix typos in behaviour, ingestor

### PR DESCRIPTION
**Pull request by danish9039**
## Which problem is this PR solving?
-  part of #701 

## Description of the changes
- fixed typo behaviour , ingestor

## How was this change tested?
- make spellcheck

## Checklist
- [ ] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [ ] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [ ] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Review by yurishkuro — COMMENTED** [review]
If all instances are fixed please remove the words from the dictionary file.

**Comment by danish9039** [comment]
> If all instances are fixed please remove the words from the dictionary file.



> If all instances are fixed please remove the words from the dictionary file.

sure

**Comment by danish9039** [comment]
> If all instances are fixed please remove the words from the dictionary file.

sure

**Review by yurishkuro — APPROVED** [review]
thanks!

**Comment by danish9039** [comment]
> thanks!

more then happy to contribute

**Pull request merged**
