### PR TITLE
Update Hugo version to 0.53

### PR DESCRIPTION
**Pull request by lucperkins**
This is a small and mostly aesthetic change that updates Hugo to version 0.53, which enables us to get rid of occasionally confusing `.Site` references.

### CODE REVIEW

**Comment by yurishkuro** [comment]
netlify doesn't seem to like this change

**Comment by lucperkins** [comment]
@yurishkuro With the regression fix, this should be okay now

**Comment by yurishkuro** [comment]
the build is breaking, maybe you need to merge master?

**Comment by lucperkins** [comment]
@yurishkuro Fixed

**Pull request merged**
