### PR TITLE
Generate docs for CLI flags

### LINKED ISSUE #250: Document flags
Document flags available in jaeger commands. We could start by creating a separate page under the deployment section.

Related https://github.com/jaegertracing/jaeger/issues/1537

### PR DESCRIPTION
**Pull request by yurishkuro**
Resolves #250 , replaces #263 and #257

### CODE REVIEW

**Comment by yurishkuro** [comment]
Changes since @lucperkins 's PR #263:
  * flag description is rendered as a separate row, to make the tables more readable (no wrapping of most flags). I also dropped "shortcut" column since we usually don't define those for all flags
  * removed documentation for `docs`, `env`, and `version` commands, as there's not a lot of value in those (we could add them if desired, but the page is already pretty long).
  * created a `data/cli/${ver]/config.json` that describes which tools the docs should be generated for and which storage options are applicable to each tool. Both the templates and the script that generates YAML files use that config as the main index. Later versions can run with a different config, e.g. if we add new storage options.
  * YAML files generated for all applicable storage types

Strictly speaking, the PR can be merged as is already, as it gives usable docs. But the following could be improved:
  * as @objectiser [mentioned](https://github.com/jaegertracing/documentation/pull/263#issuecomment-508042467), it would be better to use tabs for different storage options, as otherwise the page becomes really long
  * the right-hand sidebar menu is too long and does not fit / does not scroll. If we switch to tabs for storage types, the sidebar menu will be much smaller and manageable
  * the tables could use some styling so that the flag descriptions are not separated by dividers

**Comment by yurishkuro** [comment]
@pavolloffay @objectiser @jpkrohling do we want to merge this as is? The only real  issue is that the right sidebar is partially unusable (but navigation  is also available from the top of the page).

**Comment by objectiser** [comment]
Fine with me. Having the information available is a benefit and formatting can be improved later.

**Comment by yurishkuro** [comment]
ok, I removed the right sidebar completely, since it's not fully usable, and added some in-page navigation. Need approval to merge.

**Comment by pavolloffay** [comment]
great to see this landing here. Thanks @lucperkins @yurishkuro !

**Pull request merged**
