### PR TITLE
Versioned documentation

### PR DESCRIPTION
**Pull request by lucperkins**
@yurishkuro Okay, this is ready for review. Sorry for the trouble.

The one issue that is *not* solved here is how we handle pages that disappear between versions. That will add a fair amount of complexity so I'm thinking that might be better left for the future.

### CODE REVIEW

**Comment by lucperkins** [comment]
@yurishkuro Update: I've separated those docs out. You can now see a "Project" dropdown that will take you to News, Roadmap, Get in touch, and Report a security issue. Does this seem like a good approach?

**Comment by lucperkins** [comment]
@yurishkuro Okay, I've pushed another round of changes. Feel free to click around and let me know if there are any remaining issues.

This has actually been a really useful exercise for me figuring out how to make versioning work automatically via inference from directory names.

**Comment by yurishkuro** [comment]
not sure what happened - did #139 also contain the versioning fixes?

**Comment by lucperkins** [comment]
@yurishkuro No, #139 didn't contain the versioning fixes. This is really strange and could very well be a GitHub issue. I'll investigate.

**Comment by lucperkins** [comment]
@yurishkuro Okay, I got it figured out. Sorry for the trouble.

**Comment by yurishkuro** [comment]
🎉 ... merging ...

**Comment by yurishkuro** [comment]
Thanks, @lucperkins , this is a great milestone for the docs!

**Pull request merged**
