### PR TITLE
Fix build issue involving missing assets

### PR DESCRIPTION
**Pull request by lucperkins**
This PR resolves issue #122.

@yurishkuro FYI we should make sure to merge this *before* merging #138.

### CODE REVIEW

**Comment by yurishkuro** [comment]
@lucperkins could you elaborate on this fix? Looks like you're vendoring a Node dependency. Is there another issue that will make it unnecessary, maybe depending on some external fix?

**Comment by lucperkins** [comment]
@yurishkuro In general, I'd prefer *not* to vendor dependencies like this but I know that there have been objections to include NodeJS-y things in the build process in the past. But if you're okay with requiring users to `npm install` these assets I can remove them from the repo.

**Comment by yurishkuro** [comment]
Yeah, I prefer not to have to run npm just to build the website. So it's fine to vendor it. We can still have a make target to **refresh that module** if we need to.

**Comment by lucperkins** [comment]
@yurishkuro The only time we'd ever need to refresh is if we wanted to update the version of the CSS framework. This will be done pretty rarely so I'll keep that process manual for now.

**Pull request merged**
