### PR TITLE
Add copy to clipboard button for code snippets on Get started page.

### LINKED ISSUE #444: Add [Copy] button to code blocks
For example, on the Getting Started page we have a docker command:

image

It would be nice if the code blocks would automatically add a [Copy] button in the top right corner to copy the code snippet (or command) into the clipboard. 

The button should have a tooltip "Copy to clipboard" and when clicked it could change its title to "Copied".

@celestehorgan would you know how to do this?

### PR DESCRIPTION
**Pull request by shreyagupta30**
Hi, 
This resolves #444 .
I tried adding a copy button on the right top corner of all the code snippets. 

A preview 
Copy-button

Signed-off-by: Shreya Gupta <shreyagupta3011@gmail.com>

### CODE REVIEW

**Comment by yurishkuro** [comment]
Looks great!

Is it possible to have the button only show on hover in the box itself, instead of taking vertical space?

image

**Comment by jpkrohling** [comment]
+1, this looks fantastic!

**Comment by shreyagupta30** [comment]
> Looks great!
> 
> Is it possible to have the button only show on hover in the box itself, instead of taking vertical space?
> 
> image

I tried adding something like this but somehow the hover feature wasn't working but I will definitely try again. :+1:

**Review by yurishkuro — APPROVED** [review]
Let's merge this for now, it's already a huge improvement imo.

We may need to go through the code snippets and remove the leading `$` signs, since the Copy function includes them as well.

**Comment by shreyagupta30** [comment]
Thanks a lot @yurishkuro :D

**Pull request merged**
