### PR TITLE
Remove resources folder and add it to gitignore

### PR DESCRIPTION
**Pull request by lucperkins**
Netlify now supports the Hugo "extended" version in beta, which means that very soon we won't need to include the `resources` folder in Git (announcement [here](https://discourse.gohugo.io/t/netlify-builds-for-hugo-extended-are-working-in-beta-now/15965)). This PR is meant to be ready to merge when the Netlify update goes prime time. Any Netlify build failures in the meantime are to be expected.

### CODE REVIEW

**Comment by yurishkuro** [comment]
@lucperkins the netlify build is failing, is this blocked on some future release there?

**Comment by lucperkins** [comment]
@yurishkuro Yes. This is expected to fail until they update their build infrastructure.

**Comment by lucperkins** [comment]
@yurishkuro Okay, this is all ready to go

**Comment by yurishkuro** [comment]
Can you explain the TOCBot change? What is the workflow? Do we need Node to build docs locally?

**Comment by lucperkins** [comment]
@yurishkuro I updated that to use the same workflow for the Sass/CSS rather than having two different workflows side by side. The assets are committed to source, so Node is still not necessary.

**Comment by lucperkins** [comment]
@yurishkuro I'm referring more to the Sass sources in `themes/jaeger-docs/node_module/tocbot/src/scss`, which were previously kept in a separate `vendor` folder. The issue with that approach is that it's unclear which version of the library is being used and there's no simple upgrade path. The advantage of doing this via npm is that you can run `npm upgrade xxxxx` to update. In the past I've updated the CSS framework for the Jaeger site using this method.

We can discuss this in a different setting. I'll roll back that change and submit a separate PR. It's not necessary in this PR.

**Comment by lucperkins** [comment]
@yurishkuro This is now ready to go

**Pull request merged**
