### PR TITLE
Preparing Release 1.15.0

### PR DESCRIPTION
**Pull request by everett980**
## Short description of the changes
- Add 1.15 cli docs
- Add git tag

### CODE REVIEW

**Comment by guo0693** [comment]
Do we need to add docs in content/docs/1.15/ ?

**Comment by everett980** [comment]
> Do we need to add docs in content/docs/1.15/ ?

The readme doesn't mention it under [Publishing New Jaeger Version](https://github.com/jaegertracing/documentation#publishing-new-jaeger-version). @yurishkuro does anything need to be done wrt content/docs/1.15/?

**Comment by guo0693** [comment]
I would assume it's needed, probably no file changes, just copy over from 1.14 to 1.15 so that the website use 1.15 as the latest version:
Screen Shot 2019-11-12 at 18 56 28

**Comment by yurishkuro** [comment]
I thought both cli filed and docs are copied automatically by the CI build.

**Comment by everett980** [comment]
@pavolloffay if these two commands are the only thing that are meant to be done, then I don't have permission to do a release:
```
git tag release-1.12.0
git push origin release-1.12.0
```

**Comment by yurishkuro** [comment]
I can run those commands, but I was looking through open PRs, it would be good to clean them up first, because otherwise they will need to be changed to include the new 1.15 files.

**Comment by yurishkuro** [comment]
done autoimatically

**Pull request closed without merging**
