### PR TITLE
Add jaeger-postgresql to storage plugins list

### PR DESCRIPTION
**Pull request by robbert229**
## Which problem is this PR solving?
This PR lists the postgres-jaeger storage plugin that I maintain to the storage plugins list.

## Description of the changes
Adds a link to the storage plugin list.

## How was this change tested?
It was visually checked.
image

## Checklist
- [X] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [X] I have signed all commits
- [X] I have added unit tests for the new functionality
- [X] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Review by jkowall — APPROVED** [review]
Thanks for your contribution and the plugin, have you considered how this will work with Jaeger v2 with the new collector?

**Comment by robbert229** [comment]
Good question, as soon as v2 gets to a mature state I plan on making the migration immediately.

**Comment by yurishkuro** [comment]
@robbert229 is it implemented as a go-plugin or gRPC server? We plan to sunset the go-plugin support and only support remote servers implementing Remote Storage API (which is mostly how go-plugin also works plus some sidecar mechanics). In Jaeger-v2 the gRPC path is already supported (but we also plan to introduce a V2 Storage API that will be batch-based, not single span like V1 API).

**Comment by robbert229** [comment]
It's implemented as a gRPC Server. 

I will say that the gRPC server experience is significantly better in my opinion than the original plug-in developer experience.

**Comment by yurishkuro** [comment]
> I will say that the gRPC server experience is significantly better in my opinion than the original plug-in developer experience.

this is why we want to sunset the latter :-). https://github.com/jaegertracing/jaeger/issues/4647

**Pull request merged**
