### PR TITLE
Added mention of 'collector.queue-size-memory' in the tuning guide

### PR DESCRIPTION
**Pull request by jpkrohling**
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
@JStickler , could you review the new text?

@jkandasa could you check the flag, based on the instructions from the [PR](https://github.com/jaegertracing/jaeger/pull/1985#issuecomment-577590136), with the latest container image (`jaegertracing/jaeger-collector:latest`) ?

**Comment by jpkrohling** [comment]
Good idea. I changed the PR to include it.

**Comment by JStickler** [comment]
LGTM, my only comment is that you might want to explain why this feature is labeled "experimental" and what are the implications of that label? Are you looking for feedback on how it works?

**Comment by jpkrohling** [comment]
> Are you looking for feedback on how it works?

Yes. It's a change in the hot-path and supposed to become active when the collector is under load. This is a dangerous combination :-)

**Comment by JStickler** [comment]
Then it might be a good idea to link to where users can provide feedback.

**Pull request merged**
