### PR TITLE
Add archive traces UI configuration

### PR DESCRIPTION
**Pull request by pavolloffay**
Signed-off-by: Pavol Loffay <ploffay@redhat.com>

Resolves: https://github.com/jaegertracing/jaeger-ui/issues/7

### CODE REVIEW

**Comment by pavolloffay** [comment]
you can raise it in the UI repo

**Comment by pavolloffay** [comment]
Thinking about this, Not sure if there are more conf props for the archive. I think dependencies is an object because there are two properties.

**Comment by pavolloffay** [comment]
+1 will clarify

**Comment by tiffon** [comment]
@pavolloffay You're right, the `archiveEnabled` is a top-level property because it's a single isolated value. 

I commented with trade-offs to both approaches in the UI ticket: https://github.com/jaegertracing/jaeger-ui/issues/277#issuecomment-442321167

What do you think?

**Pull request merged**
