### PR TITLE
Release 1.20.0

### LINKED ISSUE #441: Release script fails on agent documentation, 'permission denied'
## Problem - what in Jaeger blocks you from solving the requirement?

When trying to release the documentation for v1.20, the [Travis job fails](https://travis-ci.org/github/jaegertracing/documentation/builds/731564274#L429) with the following message:

```
Status: Downloaded newer image for jaegertracing/jaeger-agent:1.20
2020/09/30 11:31:26 maxprocs: Leaving GOMAXPROCS=2: CPU quota undefined
2020/09/30 11:31:26 Generating documentation in /data
Error: open /data/jaeger-agent_docs.yaml: permission denied

Usage:
  jaeger-agent docs [flags]

Flags:
      --dir string      Directory where generate the documentation. (default "./")
      --format string   Supported formats: [md man rst yaml]. (default "md")
  -h, --help            help for docs

open /data/jaeger-agent_docs.yaml: permission denied
```

@yurishkuro have you seen this during the last release (1.19)?

### PR DESCRIPTION
**Pull request by jpkrohling**
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

## Which problem is this PR solving?
- Fixes #441
- Manual release of 1.20 docs

## Short description of the changes
- Added "--privileged" to the Docker command used by the Python script that generates CLI documentation

### CODE REVIEW

**Comment by jpkrohling** [comment]
I ran the commands from the release script manually, and here's the Docker command before this change:

```console
$ docker run --rm --interactive --volume /home/jpkroehling/Projects/src/github.com/jaegertracing/documentation/data/cli/1.20:/data -e SPAN_STORAGE_TYPE=cassandra jaegertracing/all-in-one:1.20 docs --format=yaml --dir=/data
2020/10/02 07:32:55 maxprocs: Leaving GOMAXPROCS=12: CPU quota undefined
2020/10/02 07:32:55 Generating documentation in /data
Error: open /data/jaeger-all-in-one_docs.yaml: permission denied
open /data/jaeger-all-in-one_docs.yaml: permission denied
Usage:
  jaeger-all-in-one docs [flags]

Flags:
      --dir string      Directory where generate the documentation. (default "./")
      --format string   Supported formats: [md man rst yaml]. (default "md")
  -h, --help            help for docs
```
And after this change:
```console
$ docker run --privileged --rm --interactive --volume /home/jpkroehling/Projects/src/github.com/jaegertracing/documentation/data/cli/1.20:/data -e SPAN_STORAGE_TYPE=cassandra jaegertracing/all-in-one:1.20 docs --format=yaml --dir=/data
2020/10/02 07:33:16 maxprocs: Leaving GOMAXPROCS=12: CPU quota undefined
2020/10/02 07:33:16 Generating documentation in /data
```

The resulting state of the workspace has been committed to a new branch, originating this PR.

**Review by objectiser — APPROVED** [review]

**Comment by objectiser** [comment]
Sorry @jpkrohling , only checked the CLI flags after had already approved.

**Comment by jpkrohling** [comment]
Just added a new commit with the properly generated flags. They were generated by manually running the commands from the release script.

**Comment by jpkrohling** [comment]
Looks better now. Could you please double-check, @objectiser ?

**Comment by objectiser** [comment]
@jpkrohling looks good now.

**Review by objectiser — APPROVED** [review]

**Pull request merged**
