### PR TITLE
Add mobile docs dropdown

### LINKED ISSUE #224: No sidebar menu on mobile
The top menu is folded into a button, but that only allows high level navigation. There seems to be no way to navigate between pages of the /docs.

@lucperkins

### PR DESCRIPTION
**Pull request by lucperkins**
This PR adds an example docs mobile dropdown. It's currently listed as WIP because the initial design is intended for feedback.

You can see an example here (on mobile and tablet screen sizes):

https://deploy-preview-365--jaegertracing.netlify.com/docs/1.16/

Resolves #224

### CODE REVIEW

**Comment by yurishkuro** [comment]
This does solve the problem, but it's a bit redundant, because there is already an icon for the top menu, which pretty much includes the same Docs menu, only without children items. Is it possible to extend that one instead to show more nesting in the mobile mode?

image

**Comment by lucperkins** [comment]
@yurishkuro Ah, okay, I see what you're looking for. Yes, I can make that happen.

**Comment by lucperkins** [comment]
@yurishkuro Have a look at this second attempt and let me know what you think

**Comment by yurishkuro** [comment]
I see, you made it have children permanently - I think it will work, at least until we have too many items so that in the desktop / portrait mode they won't fit vertically.

One issue I noticed is that once you make the screen smaller, the menu shows up by default, i.e. the function of the menu icon is reversed (hit [X] to show site content, hit [=] for menu).

**Comment by lucperkins** [comment]
@yurishkuro Oops! That's something I added for debugging purposes and forgot to remove. Fixed.

**Pull request merged**
