### PR TITLE
Added new troubleshooting item, 'missing ingress spans'

### PR DESCRIPTION
**Pull request by jpkrohling**
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

## Which problem is this PR solving?
- My incapacity in remembering what is wrong with my service mesh configuration...

## Short description of the changes
- Added a new troubleshooting point, explaining the cause and solution for missing ingress proxy spans

### CODE REVIEW

**Comment by objectiser** [comment]
@jpkrohling As this is more about Istio, than Jaeger, wondering whether it would be better to add to https://istio.io/faq/distributed-tracing/ - especially as it is a general tracing issue and not specific to Jaeger?

**Comment by yurishkuro** [comment]
@jpkrohling do we want to close this?

**Comment by jpkrohling** [comment]
@objectiser, did you manage to send a PR with the new Istio FAQ item? If so, I'll change this PR to link to their FAQ.

**Comment by objectiser** [comment]
@jpkrohling waiting on merge of https://github.com/istio/istio.io/pull/5266

**Comment by jpkrohling** [comment]
PR updated

**Pull request merged**
