### PR TITLE
Add tables for supported clients and client features

### LINKED ISSUE #38: Define framework for building feature matrix for client libraries
Moved from https://github.com/jaegertracing/jaeger/issues/384

## Problem

Jaeger already has 6 official client libraries, with different levels of support for different features. Ideally we want to standardize on a uniform set of features across all languages, but in practice some libs will be lagging behind others, so it would be good to have a feature matrix in the documentation.

## Proposal

Define feature matrix in a YAML file `data/clients.yaml` like this:

```yaml
features:
  - name: udp_jaeger_thrift
    description: Report spans in `jaeger.thrift` format over UDP
  - name: propagation_b3
    description: Support Zipkin's B3 headers as wire format for span context

clients:
  - name: Go
    repo: http://github.com/jaegertracing/jaeger-client-go
    features:
      udp_jaeger_thrift: Y
      propagation_b3: partial
  - name: Java
    repo: http://github.com/jaegertracing/jaeger-client-java
    features:
      udp_jaeger_thrift: Y
      propagation_b3: N
```

Ideally, the values in the fields like `description` (or all fields) would support Markdown.

## Open questions
  * can the template for rendering the table be written directly in `clients.md`?
  * if not, where do we define the template and how can we inline it in `clients.md`?

@lucperkins appreciate your input

### PR DESCRIPTION
**Pull request by lucperkins**
Fixes #38 

@yurishkuro The YAML file defining the clients is currently incomplete but otherwise I think this is more or less what you were asking for.

* [Features table](https://deploy-preview-39--jaegertracing.netlify.com/docs/client-libraries/#client-library-features)
* [Libraries table](https://deploy-preview-39--jaegertracing.netlify.com/docs/client-libraries/#official-libraries)

### CODE REVIEW

**Comment by yurishkuro** [comment]
wow, that's pretty easy & sweet.

The only change is that my intention was to create a single table from the two sections in the yaml file, that would like like:

| Feature        | [Go](./)           | [Java ](./) |
| ------------- |:-------------:| -----:|
| description1      | :white_check_mark: | :white_check_mark: |
| description2     | :white_check_mark: | :white_check_mark: |

so the template logic requires a nested loop like
```
foreach f in features
    <tr>
    <td> f.description </td>
    foreach c in clients
        <td> c[f.name] | format </td>
    </tr>
```

the name/id of the feature is only used internally, never displayed to the user

**Comment by lucperkins** [comment]
@yurishkuro Okay, I think [this](https://deploy-preview-39--jaegertracing.netlify.com/docs/client-libraries/#client-library-features) might be more in line with what you were thinking.

**Comment by yurishkuro** [comment]
awesome, that's exactly what I wanted. Thanks for the template. I can take over this PR to finish the actual yaml file.

**Comment by yurishkuro** [comment]
@lucperkins I added a whole bunch of features to the matrix and also divided the features list into groups where each group has its own header and the sub-header contains all clients to make it easier to view the table (otherwise a single header row would scroll up making it difficult to understand which column is which). You may want to sanity-check the changes in the template.

**Comment by lucperkins** [comment]
Looks good to me. The template changes strike me as quite idiomatic. +1.

**Comment by yurishkuro** [comment]
I wasn't sure if there's a convention for these style of tables that have header & subheader, and the `<thead>`  is currently empty. But if looks good then I think it's ready to merge.

**Comment by lucperkins** [comment]
+1

**Comment by yurishkuro** [comment]
Thanks again for your help, @lucperkins

**Pull request merged**
